/****************/
/* PROFESSIONAL */
/****************/

CREATE TABLE "PROFESSIONAL" (
	"ID"		NUMBER,
	"PASSWORD"	VARCHAR2(40),
	"NAME"		VARCHAR2(40),
	"PHONE"		VARCHAR2(10),
	CONSTRAINT "Q2_PROFESSIONAL_PK" PRIMARY KEY ("ID")
)
/

CREATE SEQUENCE "PROFESSIONAL_SEQ"
/

CREATE TRIGGER "BI_PROFESSIONAL"
	BEFORE INSERT ON "PROFESSIONAL"
	FOR EACH ROW
	BEGIN
		SELECT "PROFESSIONAL_SEQ".NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
/

/* Password must contain at least one number */
ALTER TABLE "PROFESSIONAL" ADD CONSTRAINT "PROFESSIONAL_CK"
CHECK (REGEXP_LIKE(PASSWORD, '[[:digit:]]+', 'i'))
/

/***********/
/* PATIENT */
/***********/

CREATE TABLE "PATIENT" (
	"ID"				NUMBER,
	"PASSWORD"			VARCHAR2(40),
	"NAME"				VARCHAR2(40),
	"ADDRESS"			VARCHAR2(400),
	"PHONE"				VARCHAR2(10),
	"PROFESSIONAL_ID"	NUMBER,
	CONSTRAINT "Q2_PATIENT_PK" PRIMARY KEY ("ID")
)
/

CREATE SEQUENCE "PATIENT_SEQ"
/

CREATE TRIGGER "BI_PATIENT"
	BEFORE INSERT ON "PATIENT"
	FOR EACH ROW
	BEGIN
		SELECT "PATIENT_SEQ".NEXTVAL INTO :NEW.ID FROM DUAL;
	END;
/

ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_FK"
FOREIGN KEY ("PROFESSIONAL_ID") REFERENCES "PROFESSIONAL" ("ID")
/

/* Password must contain at least one number */
ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_CK"
CHECK (REGEXP_LIKE(PASSWORD, '[[:digit:]]+', 'i'))
/

/***************/
/* DIAG_METHOD */
/***************/

CREATE TABLE "DIAG_METHOD" (
	"ID"		VARCHAR2(12),
	"CONDITION"	VARCHAR2(512),
	"PROCESS"	VARCHAR2(512),
	"TOOL"		VARCHAR2(64),
	"METHOD"	VARCHAR2(512),
	CONSTRAINT "Q2_DIAG_METHOD_PK" PRIMARY KEY ("ID")
)
/

ALTER TABLE "DIAG_METHOD" ADD CONSTRAINT "Q2_DIAG_METHOD_U"
UNIQUE ("CONDITION")
/

CREATE SEQUENCE "DIAG_METHOD_SEQ"
/

CREATE TRIGGER "BI_DIAG_METHOD"
	BEFORE INSERT ON "DIAG_METHOD"
	FOR EACH ROW
	BEGIN
		SELECT CONCAT(SUBSTR(:NEW.CONDITION, 1, 3), 
				TO_CHAR("DIAG_METHOD_SEQ".NEXTVAL)) INTO :NEW.ID FROM DUAL;
	END;
/

/***********************/
/* PATIENT_DIAG_METHOD */
/***********************/

CREATE TABLE "PATIENT_DIAG_METHOD" (
	"PATIENT_ID"		NUMBER,
	"DIAG_METHOD_ID"	VARCHAR2(12),
	CONSTRAINT "Q2_PATIENT_DIAG_METHOD_PK" 
			PRIMARY KEY ("PATIENT_ID", "DIAG_METHOD_ID")
)
/

ALTER TABLE "PATIENT_DIAG_METHOD" ADD CONSTRAINT "PATIENT_DIAG_METHOD_FK1"
FOREIGN KEY ("PATIENT_ID") REFERENCES "PATIENT" ("ID")
/

ALTER TABLE "PATIENT_DIAG_METHOD" ADD CONSTRAINT "PATIENT_DIAG_METHOD_FK2"
FOREIGN KEY ("DIAG_METHOD_ID") REFERENCES "DIAG_METHOD" ("ID")
/

/*************/
/* DIAG_DATA */
/*************/

CREATE TABLE "DIAG_DATA" (
	"ID"				NUMBER,
	"DIAG_METHOD_ID"	VARCHAR(12),
	"PATIENT_ID"		NUMBER,
	"VALUE"				VARCHAR(20),
	"MEASURE_DATE"		DATE,
	CONSTRAINT "Q2_DIAG_DATA_PK" PRIMARY KEY ("ID", "DIAG_METHOD_ID")
)
/

CREATE SEQUENCE "DIAG_DATA_SEQ"
/

CREATE TRIGGER "BI_DIAG_DATA"
	BEFORE INSERT ON "DIAG_DATA"
	FOR EACH ROW
	BEGIN
		SELECT "DIAG_DATA_SEQ".NEXTVAL INTO :NEW.ID FROM DUAL;
		:NEW.MEASURE_DATE := SYSDATE;
	END;
/

ALTER TABLE "DIAG_DATA" ADD CONSTRAINT "DIAG_DATA_FK1"
FOREIGN KEY ("DIAG_METHOD_ID") REFERENCES "DIAG_METHOD" ("ID")
/

ALTER TABLE "DIAG_DATA" ADD CONSTRAINT "DIAG_DATA_FK2"
FOREIGN KEY ("PATIENT_ID") REFERENCES "PATIENT" ("ID")
/